### ISSUE TITLE
Параметры эллипсоида Крассовского

### ISSUE THREAD

**Issue by Belikov** [GeorgGrebenyuk/MSK_for-Autodesk-Civil-3D#1]
Терзаюсь вопросом, зачем у вашего эллипсоида Крассовского (Krasovsky-SK42/95) отличные от встроенного параметры? Ведь если у нас регламентированы только a=6378245 и f=1/298,3, то остальное вычисляется сколь угодно точно:

f=0,00335232986925913509889373114314
b=6356863,0187730472678511565538049‬
e=0,08181333401693114735842128091786

В родном цивиловском (KRASOV) точность не запредельная: очевидно, используется b с точностью до 8-го знака, а сжатие затем вычисляется:

b=6356863.01877305 => f=0,00335232986925871

Но у вас малая полуось b=6356863.0187747 и сжатие f=0.00335232986899991 — откуда? почему?

**Comment by GeorgGrebenyuk** [comment]
@Belikov , а... в том то и вся соль, что Сивиловская"точность" не даст задать такие параметры. Там система настроена так, что при двух заданных параметрах прочие считаются автоматом; для проверки попробуйте-ка сами вставить значение полярного сжатия = 0.00335232986925913, сохраните изменения и откройте снова - вы это число не увидите. 
Поэтому максимально приблизиться к величине полярного сжатия = 1/298,3 создатели KRASOV смогли не при его прямом задании, а при задании радиуса малой полуоси [назначив b= a-a*_a_]. Как вы можете заметить - число дробных знаков для полярного сжатия очень ограничено, по причине чего сильно прыгают зависимые от него значения радиусов полуосей, от чего такие и цифры

Отчего же так у меня? Хм, действительно, хороший вопрос; причем, я точно помню, что не раз и не два подходил к этому, но оставлял как есть. Я хотел было переназначить еще параметры, как у системного KRASOV, но то ли забыл, то ли сделал это в другой редакции (оставаясь свято уверенным, что в этой редакции всё верно). В общем да - тут явная ошибка в текущих определениях, и их надо взять по образцу системных (сборку обновил с учетом этой поправки)

**Comment by Belikov** [comment]
Я попробовал и убедился, что вы правы — более точно, чем KRASOV невозможно определить эллипсоид в Civil 3D. Спасибо за багфикс и ещё одно за всю эту работу!
